###
### Buscar um pagamento mensal por ID
GET http://localhost:8000/paymentMonthly/15
Content-Type: application/json
Accept: application/json

###

### Listar todos os pagamentos mensais
GET http://localhost:8000/paymentMonthly
Content-Type: application/json
Accept: application/json

###

### Criar um novo pagamento mensal
POST http://localhost:8000/paymentMonthly
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "type": "mensal",
  "ref_year": "2025",
  "amount": 50.00,
  "status": "Confirmar"
}

###

### Atualizar um pagamento mensal
PATCH http://localhost:8000/paymentMonthly/confirmPayment/28
Content-Type: application/json
Accept: application/json

{
  "status": "Confirmado"
}

###

### Excluir um pagamento mensal
DELETE http://localhost:8000/paymentMonthly/15
Content-Type: application/json
Accept: application/json